### PR TITLE
Generate a rubocop todo

### PR DESCRIPTION
**Pull request by hennevogel**
We don't have a Gemfile.lock and only loosely specify the rubocop version in our gemspec, so we get new rubocop versions in CI all the time...

### CODE REVIEW

**Comment by hennevogel** [comment]
See all the other failing PRs before this...

**Comment by dmarcoux** [comment]
What speaks against pinning a specific version of RuboCop as a development dependency? This would ensure we have a reproducible CI.

**Comment by hennevogel** [comment]
> What speaks against pinning a specific version of RuboCop as a development dependency? 

Bitrot? :)

**Review by dmarcoux — APPROVED** [review]
After sleeping on it, I think this is at least a step in the right direction. It does mean that we need to regenerate the RuboCop TODOs whenever there's a new RuboCop version.

If we end up pinning RuboCop, we can always do it in another PR.

**Pull request merged**
