### PR TITLE
Fix reason retrieval while checking for deployment lock

### PR DESCRIPTION
**Pull request by danidoni**
It's better to "store" the reason in the state of the deployment in the deployment status than in the deployment itself because each locking can have its own reason.

### CODE REVIEW

**Review by saraycp — APPROVED** [review]
I agree, the reason justifies the change of status, so I see it more related to `deployment_status`.

This PR also ensures that  the `check-lock` command returns a non-empty `reason` when the deployments where locked, this was wrong before.

AFAIK, these changes don't require any change in `ansible_obs`, since the command and the output keep the same, right?

```
# bin/ogd -l --reason 'I have a good reason, trust me'
=> {"status":"ok","reason":"I have a good reason, trust me"}

# bin/ogd -c
=> {"status":"locked","reason":"I have a good reason, trust me"}
```

**Comment by danidoni** [comment]
> ```
> # bin/ogd -l --reason 'I have a good reason, trust me'
> => {"status":"ok","reason":"I have a good reason, trust me"}
> 
> # bin/ogd -c
> => {"status":"locked","reason":"I have a good reason, trust me"}
> ```

Right!

**Comment by eduardoj** [comment]
The second commit "Store the reason into the description field of the deployment status" makes it not possible to store a message of more than 140 characters. See https://docs.github.com/en/rest/reference/repos#create-a-deployment-status

This is not a stopper, but something that must be taken into account.

**Comment by danidoni** [comment]
> The second commit "Store the reason into the description field of the deployment status" makes it not possible to store a message of more than 140 characters. See https://docs.github.com/en/rest/reference/repos#create-a-deployment-status
> 
> This is not a stopper, but something that must be taken into account.

Good catch!

**Comment by danidoni** [comment]
> The second commit "Store the reason into the description field of the deployment status" makes it not possible to store a message of more than 140 characters. See https://docs.github.com/en/rest/reference/repos#create-a-deployment-status
> 
> This is not a stopper, but something that must be taken into account.

I've added an error check when the reason is longer than 140 characters. Please, can you review it again?

**Review by eduardoj — APPROVED** [review]

**Pull request merged**
